export const BASE_URL = 'http://51.250.21.144:5001';

export const DEFAULT_NEW_DISCIPLINE_VALUES = {
  lecturesAccodingToPlan: 0,
  labWorkAccordingToPlan: 0,
  practiceAccordingToPlan: 0,
  mpcAccordingToPlan: 0,
  akrAccordingToPlan: 0,
  courseProjectAccordingToPlan: 0,
  сonsultationsAccordingToPlan: 0,
  reviewsAccordingToPlan: 0,
  testsAccordingToPlan: 0,
  examsAccordingToPlan: 0,
  educationalPracticeAccordingToPlan: 0,
  productionPracticeAccordingToPlan: 0,
  graduationProjectAccordingToPlan: 0,
  gekgakAccordingToPlan: 0,
  postgraduateAndMasterDegreeAccordingToPlan: 0,
  allHoursAccordingToPlan: 0,
  lectures: 0,
  labWork: 0,
  practice: 0,
  mpc: 0,
  akr: 0,
  courseProject: 0,
  сonsultations: 0,
  reviews: 0,
  tests: 0,
  exams: 0,
  educationalPractice: 0,
  productionPractice: 0,
  graduationProject: 0,
  gekgak: 0,
  postgraduateAndMasterDegree: 0,
  examFlag: true,
  offsetFlag: true,
  courseProjectFlag: true,
  diplomaFlag: true,
  gekgakFlag: true,
  educationalPracticeFlag: true,
  productionPracticeFlag: true,
  postgraduateAndMasterDegreeFlag: true,
};

export const DEFAULT_NEW_DEPARTMENT_WORK_VALUES = {
  diciplineId: 0,
  groupId: 0,
  courseProject: 0,
  testsReview: 0,
  exams: 0,
  courseWork: 0,
  inZe: 0,
  inHours: 0,
  lecturesTotal: 0,
  labWorkTotal: 0,
  practiceTotal: 0,
  individualSessions: 0,
  modularRatingSystem: 0,
  consultations: 0,
  offsets: 0,
  educationalPractice: 0,
  productionPractice: 0,
  diplomaDesign: 0,
  gekgak: 0,
  postgraduateAndMasterDegree: 0,
  totalHours: 0,
  budgetFlag: true,
};
